# suppress inspection "UnusedProperty" for whole file
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: ticketservice
  config:
    enabled: true
    import: "configserver:http://localhost:8888"

